# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  terraform: circleci/terraform@3.0.1

jobs:
  validate:
    # Use the Terraform orb to produce a Terraform plan and add a comment as a GitHub user
    executor: terraform/default
    steps:
      - checkout
      - terraform/validate:
          path: ./terraform
  plan_comment:
    parameters:
    docker:
      - image: cloudposse/github-commenter:0.9.0
    working_directory: ./terraform
    steps:
      - checkout
      - terraform/plan:
          path: "./terraform"
      - run:
          name: Post plan as PR comment
          command: |-
            touch out.txt
            terraform show -no-color ./terraform/plan.out >> out.txt
            cat out.txt | github-commenter \
              -owner ${CIRCLE_PROJECT_USERNAME} \
              -repo ${CIRCLE_PROJECT_REPONAME} \
              -number ${CIRCLE_PR_NUMBER} \
              -delete-comment-regex "Output from" \
              -type pr \
              -template_file .circleci/plan-comment.tpl
  apply:
    parameters:
    executor: terraform/default
    steps:
      - checkout
      - terraform/apply:
          path: ./terraform

workflows:
  version: 2
  pr-workflow:
    condition:
      not:
        equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - validate
      - plan_comment:
          name: plan_comment          
          context:
            - github
            - aws
          requires:
            - validate
  main-workflow:
    when:
      condition:
        equal: [main, << pipeline.git.branch >> ]
    jobs:
      - apply:
          name: apply
          context:
            - aws